language: go
dist: xenial

go:
  - "1.11"
  - "1.12"

cache:
  directories:
    - $HOME/bin
    - $HOME/libc
    - $HOME/.cache/go-build
    - $HOME/gopath/pkg/mod

before_install:
  # xenial packages are broken and do no allow to cross-compile for both 386 and arm.
  # 386 requires gcc-multilib installed and arm requires gcc-arm-linux-gnueabi,
  # but these packages are conflicting. This is a hacky way to install 386 headers.
  - sudo dpkg --add-architecture i386
  - sudo apt-get update
  - sudo apt-get install -y -q linux-libc-dev:i386 lib32gcc-5-dev lib32stdc++-5-dev
  - test -d $HOME/libc/usr/lib/x86_64-linux-gnu/ || (
      mkdir -p $HOME/libc                                                                                   &&
      wget http://security.ubuntu.com/ubuntu/pool/main/g/gcc-5/libstdc++6_5.4.0-6ubuntu1~16.04.10_amd64.deb &&
      dpkg-deb -x ./libstdc++6_5.4.0-6ubuntu1~16.04.10_amd64.deb $HOME/libc
    )
  - export LD_LIBRARY_PATH=$HOME/libc/usr/lib/x86_64-linux-gnu/
  - which clang-format || (
      wget http://releases.llvm.org/6.0.1/clang+llvm-6.0.1-x86_64-linux-gnu-ubuntu-14.04.tar.xz &&
      tar -xf ./clang+llvm-6.0.1-x86_64-linux-gnu-ubuntu-14.04.tar.xz                           &&
      cp clang+llvm-6.0.1-x86_64-linux-gnu-ubuntu-14.04/bin/clang-format $HOME/bin/
    )
  - clang-format --version

install: true

script:
  - make install_prerequisites
  - make presubmit

after_success:
  - bash <(curl -s https://codecov.io/bash)

# If the build fails because some code in not formatted, it's nice to see the diffs after formatting.
after_failure:
  - git diff --name-only
  - git diff
